nome = input("Digite seu nome:")
telefone = input("Digite o seu número de telefone:")
email = input("Digite o seu e-mail:")
endereco = input("Digite o seu endereço:")
idade = input("Digite sua idade:")
sexo = input("Digite o seu sexo:")
salario = input("Digite o valor do seu salário:")

print("Nome:", nome)
print("Telefone:", telefone)
print("E-mail:", email)
print("Endereço:", endereco)
print("Idade:", idade)
print("Sexo:", sexo)
print("Salário:", salario)